---
- name: infoblox next available ip
  debug:
    msg: "IP address from infoblox is: {{ infoblox_response.json.ipv4addrs[0].ipv4addr }}"

- name: launch an instance
  os_server:
    state: present
    auth:
      auth_url: "{{ osp_server }}"
      username: "{{ osp_user }}"
      password: "{{ osp_pass }}"
      project_name: "{{ osp_tenant }}"
    name: "{{ osp_instance_name }}"
    image: "{{ osp_image }}"
    key_name: "{{ osp_key }}"
    timeout: 200
    flavor: "{{ osp_flavor }}"
    security_groups: "{{ osp_security_group }}"
    network: "{{ osp_network }}"
    floating_ips: 
      - "{{ infoblox_response.json.ipv4addrs[0].ipv4addr }}"
    wait: True
    userdata: |
      #cloud-config
      ssh_authorized_keys:
        - "{{ osp_public_key }}"
  register: instance
  delegate_to: "{{ control_machine }}"

- name: add the public IP address as a fact
  set_fact:
    ansible_default_ipv4:
      address: "{{ infoblox_response.json.ipv4addrs[0].ipv4addr }}"
    cacheable: True

# - name: create volumes
#   os_volume:
#     auth:
#       auth_url: "{{ osp_server }}"
#       username: "{{ osp_user }}"
#       password: "{{ osp_pass }}"
#       project_name: "{{ osp_tenant }}"
#     state: present
#     size: "{{ osp_volume_size }}"
#     display_name: "{{ osp_instance_name }}-{{ osp_volume_name }}"
#   delegate_to: "{{ control_machine }}"

# - name: attach volumes  
#   os_server_volume:
#     auth:
#       auth_url: "{{ osp_server }}"
#       username: "{{ osp_user }}"
#       password: "{{ osp_pass }}"
#       project_name: "{{ osp_tenant }}"
#     state: present    
#     server: "{{ osp_instance_name }}"
#     volume: "{{ osp_instance_name }}-{{ osp_volume_name }}"
#   delegate_to: "{{ control_machine }}"