---
- name: Enforces a given number of application instances in OpenStack to exist
  hosts: all
  gather_facts: false  
  vars:
    prefix: application-sla-test
    sla: 1
    control_machine: tower
    msg: "The number of instances that will be created to meet the application SLA is"
  
  tasks:
  - name: Get instances that start with '{{ prefix }}'
    os_server_facts:
      auth:
        auth_url: "{{ osp_server }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_tenant }}"
      server: "{{ prefix }}*"
    delegate_to: "{{ control_machine }}"  

  - debug:
      var: openstack_servers      

  - name: Determine number of required instances to create
    vars:
      powered_on_instances: "[?power_state==`{{ osp_state}}`]"
      instances: "{{ openstack_servers|json_query(powered_on_instances) }}"
      required_instances: "{{ sla - instances|length }}"
    set_fact:
      count: "{{ required_instances }}"
    register: instances
    changed_when: instances.ansible_facts.count|int > 0

  - name: cache instance name
    set_fact:
      name: "{{ prefix }}-{{ 999 | random | to_uuid }}"
    register: instance

  - name: provision instances
    vars:
      osp_instance_name: "{{ instance.ansible_facts.name }}"
    include_role:
      name: provision
    when: instances.ansible_facts.count|int > 0  

  - name: Add instance to a group
    add_host:
      name: "{{ instance.ansible_facts.name }}"
      groups: provisioned_instance
    when: instances.ansible_facts.count|int > 0        

  - name: update cloudforms service
    include_role:
      name: updateservice
    when: (manageiq is defined) and (instances.ansible_facts.count|int > 0)

# Second play
- name: Configure instance
  hosts: provisioned_instance
  become: true

  tasks:
  - name: configure instance
    include_role:
      name: installpackage 
      
