---
- name: delete an instance
  os_server:
    state: absent
    auth:
      auth_url: "{{ osp_server }}"
      username: "{{ osp_user }}"
      password: "{{ osp_pass }}"
      project_name: "{{ osp_tenant }}"
    name: "{{ inventory_hostname }}"
  delegate_to: localhost

- name: delete volumes
  os_volume:
    auth:
      auth_url: "{{ osp_server }}"
      username: "{{ osp_user }}"
      password: "{{ osp_pass }}"
      project_name: "{{ osp_tenant }}"  
    state: absent
    display_name: "{{ inventory_hostname }}-{{ item['name'] }}"  
  with_flattened: 
    - "{{ hostvars[inventory_hostname]['docker-volumes'] }}"
    - "{{ hostvars[inventory_hostname]['nfs-volumes'] }}"
  delegate_to: localhost  
    
